package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

type generatedBuiltinSuite struct {
	Tests []generatedBuiltinTest `yaml:"tests"`
}

type generatedBuiltinTest struct {
	Name   string                 `yaml:"name"`
	Code   string                 `yaml:"code"`
	Expect generatedBuiltinExpect `yaml:"expect"`
}

type generatedBuiltinExpect struct {
	Value any `yaml:"value"`
}

type signature struct {
	Name     string
	MinArg   int64
	MaxArg   int64
	ArgTypes []int64
}

func main() {
	root := filepath.Join("..", "moo-conformance-tests", "src", "moo_conformance", "_tests", "generated_builtins")
	matches, err := filepath.Glob(filepath.Join(root, "*.yaml"))
	if err != nil {
		fail(err)
	}
	if len(matches) == 0 {
		fail(fmt.Errorf("no generated builtin YAMLs found under %s", root))
	}

	signatures := make(map[string]signature)
	for _, path := range matches {
		sig, ok, err := loadSignature(path)
		if err != nil {
			fail(fmt.Errorf("%s: %w", path, err))
		}
		if ok {
			signatures[sig.Name] = sig
		}
	}

	names := make([]string, 0, len(signatures))
	for name := range signatures {
		names = append(names, name)
	}
	sort.Strings(names)

	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/gen_builtin_signatures; DO NOT EDIT.\n")
	buf.WriteString("package builtins\n\n")
	buf.WriteString("var generatedFunctionSignatures = map[string]functionSignature{\n")
	for _, name := range names {
		sig := signatures[name]
		buf.WriteString(fmt.Sprintf("\t%q: {minArg: %d, maxArg: %d, argTypes: []int64{", sig.Name, sig.MinArg, sig.MaxArg))
		for i, argType := range sig.ArgTypes {
			if i > 0 {
				buf.WriteString(", ")
			}
			buf.WriteString(strconv.FormatInt(argType, 10))
		}
		buf.WriteString("}},\n")
	}
	buf.WriteString("}\n")

	if _, err := os.Stdout.Write(buf.Bytes()); err != nil {
		fail(err)
	}
}

func loadSignature(path string) (signature, bool, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return signature{}, false, err
	}

	var suite generatedBuiltinSuite
	if err := yaml.Unmarshal(data, &suite); err != nil {
		return signature{}, false, err
	}

	for _, test := range suite.Tests {
		if !strings.Contains(test.Name, "_function_info_signature_matches_source") {
			continue
		}
		rawValue, ok := test.Expect.Value.([]any)
		if !ok {
			return signature{}, false, fmt.Errorf("unexpected value shape for %s", test.Name)
		}
		if len(rawValue) != 4 {
			return signature{}, false, fmt.Errorf("unexpected value shape for %s", test.Name)
		}

		name, ok := rawValue[0].(string)
		if !ok {
			return signature{}, false, fmt.Errorf("builtin name is not a string")
		}
		minArg, err := toInt64(rawValue[1])
		if err != nil {
			return signature{}, false, fmt.Errorf("minArg: %w", err)
		}
		maxArg, err := toInt64(rawValue[2])
		if err != nil {
			return signature{}, false, fmt.Errorf("maxArg: %w", err)
		}

		rawArgTypes, ok := rawValue[3].([]any)
		if !ok {
			return signature{}, false, fmt.Errorf("argTypes is not a list")
		}
		argTypes := make([]int64, 0, len(rawArgTypes))
		for _, raw := range rawArgTypes {
			argType, err := toInt64(raw)
			if err != nil {
				return signature{}, false, fmt.Errorf("argType: %w", err)
			}
			argTypes = append(argTypes, argType)
		}

		return signature{
			Name:     name,
			MinArg:   minArg,
			MaxArg:   maxArg,
			ArgTypes: argTypes,
		}, true, nil
	}

	return signature{}, false, nil
}

func toInt64(v any) (int64, error) {
	switch val := v.(type) {
	case int:
		return int64(val), nil
	case int64:
		return val, nil
	case uint64:
		return int64(val), nil
	case float64:
		return int64(val), nil
	default:
		return 0, fmt.Errorf("unsupported integer value %T", v)
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
