package builtins

import "github.com/MongooseMoo/barn/config"

// BaseDescriptors returns independent, complete construction inputs for Barn builtins.
// VM-owned eval and pass are contributed by vm before construction.
func BaseDescriptors() []Descriptor {
	return []Descriptor{
		{Name: "typeof", Implementation: builtinTypeof, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{-1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "tostr", Implementation: builtinTostr, Signature: &Signature{MinArgs: 0, MaxArgs: -1, ArgTypes: []int64{}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "toint", Implementation: builtinToint, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{-1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "tofloat", Implementation: builtinTofloat, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{-1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "toliteral", Implementation: builtinToliteral, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{-1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "toobj", Implementation: builtinToobj, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{-1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "equal", Implementation: builtinEqual, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{-1, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "length", Implementation: builtinLength, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{-1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "strsub", Implementation: builtinStrsub, Signature: &Signature{MinArgs: 3, MaxArgs: 4, ArgTypes: []int64{2, 2, 2, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "strtr", Implementation: builtinStrtr, Signature: &Signature{MinArgs: 3, MaxArgs: 4, ArgTypes: []int64{2, 2, 2, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "index", Implementation: builtinIndex, Signature: &Signature{MinArgs: 2, MaxArgs: 4, ArgTypes: []int64{2, 2, -1, 0}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "rindex", Implementation: builtinRindex, Signature: &Signature{MinArgs: 2, MaxArgs: 4, ArgTypes: []int64{2, 2, -1, 0}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "strcmp", Implementation: builtinStrcmp, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{2, 2}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "upcase", Implementation: builtinUpcase, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{2}, PlainArityError: true}, Visibility: Hidden, Effect: Transactional, Capability: config.BarnExtensions},
		{Name: "downcase", Implementation: builtinDowncase, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{2}, PlainArityError: true}, Visibility: Hidden, Effect: Transactional, Capability: config.BarnExtensions},
		{Name: "capitalize", Implementation: builtinCapitalize, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{2}, PlainArityError: true}, Visibility: Hidden, Effect: Transactional, Capability: config.BarnExtensions},
		{Name: "explode", Implementation: builtinExplode, Signature: &Signature{MinArgs: 1, MaxArgs: 3, ArgTypes: []int64{2, 2, 0}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "implode", Implementation: builtinImplode, Signature: &Signature{MinArgs: 1, MaxArgs: 2, ArgTypes: []int64{4, 2}, PlainArityError: true}, Visibility: Hidden, Effect: Transactional, Capability: config.BarnExtensions},
		{Name: "trim", Implementation: builtinTrim, Signature: &Signature{MinArgs: 1, MaxArgs: 2, ArgTypes: []int64{2, 2}, PlainArityError: true}, Visibility: Hidden, Effect: Transactional, Capability: config.BarnExtensions},
		{Name: "ltrim", Implementation: builtinLtrim, Signature: &Signature{MinArgs: 1, MaxArgs: 2, ArgTypes: []int64{2, 2}, PlainArityError: true}, Visibility: Hidden, Effect: Transactional, Capability: config.BarnExtensions},
		{Name: "rtrim", Implementation: builtinRtrim, Signature: &Signature{MinArgs: 1, MaxArgs: 2, ArgTypes: []int64{2, 2}, PlainArityError: true}, Visibility: Hidden, Effect: Transactional, Capability: config.BarnExtensions},
		{Name: "match", Implementation: builtinMatch, Signature: &Signature{MinArgs: 2, MaxArgs: 3, ArgTypes: []int64{2, 2, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "rmatch", Implementation: builtinRmatch, Signature: &Signature{MinArgs: 2, MaxArgs: 3, ArgTypes: []int64{2, 2, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "substitute", Implementation: builtinSubstitute, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{2, 4}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "all_members", Implementation: builtinAllMembers, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{-1, 4}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "chr", Implementation: builtinChr, Signature: &Signature{MinArgs: 0, MaxArgs: -1, ArgTypes: []int64{}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "parse_ansi", Implementation: builtinParseAnsi, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{2}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "remove_ansi", Implementation: builtinRemoveAnsi, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{2}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "listappend", Implementation: builtinListappend, Signature: &Signature{MinArgs: 2, MaxArgs: 3, ArgTypes: []int64{4, -1, 0}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "listinsert", Implementation: builtinListinsert, Signature: &Signature{MinArgs: 2, MaxArgs: 3, ArgTypes: []int64{4, -1, 0}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "listdelete", Implementation: builtinListdelete, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{4, 0}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "listset", Implementation: builtinListset, Signature: &Signature{MinArgs: 3, MaxArgs: 3, ArgTypes: []int64{4, -1, 0}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "setadd", Implementation: builtinSetadd, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{4, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "setremove", Implementation: builtinSetremove, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{4, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "is_member", Implementation: builtinIsMember, Signature: &Signature{MinArgs: 2, MaxArgs: 3, ArgTypes: []int64{-1, -1, 0}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "sort", Implementation: builtinSort, Signature: &Signature{MinArgs: 1, MaxArgs: 4, ArgTypes: []int64{4, 4, 0, 0}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "reverse", Implementation: builtinReverse, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{-1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "unique", Implementation: builtinUnique, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{4}, PlainArityError: true}, Visibility: Hidden, Effect: Transactional, Capability: config.BarnExtensions},
		{Name: "slice", Implementation: builtinSlice, Signature: &Signature{MinArgs: 1, MaxArgs: 3, ArgTypes: []int64{4, -1, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "abs", Implementation: builtinAbs, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{-2}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "min", Implementation: builtinMin, Signature: &Signature{MinArgs: 1, MaxArgs: -1, ArgTypes: []int64{-2}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "max", Implementation: builtinMax, Signature: &Signature{MinArgs: 1, MaxArgs: -1, ArgTypes: []int64{-2}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "random", Implementation: builtinRandom, Signature: &Signature{MinArgs: 0, MaxArgs: 2, ArgTypes: []int64{0, 0}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "frandom", Implementation: builtinFrandom, Signature: &Signature{MinArgs: 1, MaxArgs: 2, ArgTypes: []int64{9, 9}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "reseed_random", Implementation: builtinReseedRandom, Signature: &Signature{MinArgs: 0, MaxArgs: 0, ArgTypes: []int64{}}, Visibility: Public, Effect: Irreversible, Capability: config.Core},
		{Name: "sqrt", Implementation: builtinSqrt, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{9}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "sin", Implementation: builtinSin, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{9}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "cos", Implementation: builtinCos, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{9}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "tan", Implementation: builtinTan, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{9}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "asin", Implementation: builtinAsin, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{9}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "acos", Implementation: builtinAcos, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{9}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "acosh", Implementation: builtinAcosh, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{9}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "atan", Implementation: builtinAtan, Signature: &Signature{MinArgs: 1, MaxArgs: 2, ArgTypes: []int64{9, 9}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "atan2", Implementation: builtinAtan2, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{9, 9}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "asinh", Implementation: builtinAsinh, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{9}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "atanh", Implementation: builtinAtanh, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{9}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "sinh", Implementation: builtinSinh, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{9}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "cosh", Implementation: builtinCosh, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{9}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "tanh", Implementation: builtinTanh, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{9}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "exp", Implementation: builtinExp, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{9}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "log", Implementation: builtinLog, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{9}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "log10", Implementation: builtinLog10, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{9}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "cbrt", Implementation: builtinCbrt, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{9}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "round", Implementation: builtinRound, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{9}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "ceil", Implementation: builtinCeil, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{9}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "floor", Implementation: builtinFloor, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{9}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "trunc", Implementation: builtinTrunc, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{9}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "floatstr", Implementation: builtinFloatstr, Signature: &Signature{MinArgs: 2, MaxArgs: 3, ArgTypes: []int64{9, 0, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "distance", Implementation: builtinDistance, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{4, 4}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "relative_heading", Implementation: builtinRelativeHeading, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{4, 4}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "simplex_noise", Implementation: builtinSimplexNoise, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{4}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "mapkeys", Implementation: builtinMapkeys, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{10}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "mapvalues", Implementation: builtinMapvalues, Signature: &Signature{MinArgs: 1, MaxArgs: -1, ArgTypes: []int64{10}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "mapdelete", Implementation: builtinMapdelete, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{10, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "maphaskey", Implementation: builtinMaphaskey, Signature: &Signature{MinArgs: 2, MaxArgs: 3, ArgTypes: []int64{10, -1, 0}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "mapmerge", Implementation: builtinMapmerge, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{10, 10}, PlainArityError: true}, Visibility: Hidden, Effect: Transactional, Capability: config.BarnExtensions},
		{Name: "create", Implementation: builtinCreate, Signature: &Signature{MinArgs: 1, MaxArgs: 4, ArgTypes: []int64{-1, -1, -1, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "recycle", Implementation: builtinRecycle, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{-1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "valid", Implementation: builtinValid, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{-1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "max_object", Implementation: builtinMaxObject, Signature: &Signature{MinArgs: 0, MaxArgs: 0, ArgTypes: []int64{}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "parent", Implementation: builtinParent, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{-1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "parents", Implementation: builtinParents, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{-1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "children", Implementation: builtinChildren, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{-1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "ancestors", Implementation: builtinAncestors, Signature: &Signature{MinArgs: 1, MaxArgs: 2, ArgTypes: []int64{-1, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "descendants", Implementation: builtinDescendants, Signature: &Signature{MinArgs: 1, MaxArgs: 2, ArgTypes: []int64{-1, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "isa", Implementation: builtinIsa, Signature: &Signature{MinArgs: 2, MaxArgs: 3, ArgTypes: []int64{-1, -1, 0}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "chparent", Implementation: builtinChparent, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{-1, 1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "chparents", Implementation: builtinChparents, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{-1, 4}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "move", Implementation: builtinMove, Signature: &Signature{MinArgs: 2, MaxArgs: 3, ArgTypes: []int64{1, 1, 0}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "is_player", Implementation: builtinIsPlayer, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "set_player_flag", Implementation: builtinSetPlayerFlag, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{1, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "players", Implementation: builtinPlayers, Signature: &Signature{MinArgs: 0, MaxArgs: 0, ArgTypes: []int64{}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "occupants", Implementation: builtinOccupants, Signature: &Signature{MinArgs: 1, MaxArgs: 4, ArgTypes: []int64{4, -1, 0, 0}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "renumber", Implementation: builtinRenumber, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "new_waif", Implementation: builtinNewWaif, Signature: &Signature{MinArgs: 0, MaxArgs: 0, ArgTypes: []int64{}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "object_bytes", Implementation: builtinObjectBytes, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{-1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "properties", Implementation: builtinProperties, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{-1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "property_info", Implementation: builtinPropertyInfo, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{-1, 2}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "set_property_info", Implementation: builtinSetPropertyInfo, Signature: &Signature{MinArgs: 3, MaxArgs: 3, ArgTypes: []int64{-1, 2, 4}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "add_property", Implementation: builtinAddProperty, Signature: &Signature{MinArgs: 4, MaxArgs: 4, ArgTypes: []int64{-1, 2, -1, 4}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "delete_property", Implementation: builtinDeleteProperty, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{-1, 2}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "clear_property", Implementation: builtinClearProperty, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{-1, 2}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "is_clear_property", Implementation: builtinIsClearProperty, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{-1, 2}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "respond_to", Implementation: builtinRespondTo, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{-1, 2}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "verbs", Implementation: builtinVerbs, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{-1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "verb_info", Implementation: builtinVerbInfo, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{-1, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "verb_args", Implementation: builtinVerbArgs, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{-1, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "verb_code", Implementation: builtinVerbCode, Signature: &Signature{MinArgs: 2, MaxArgs: 4, ArgTypes: []int64{-1, -1, -1, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "add_verb", Implementation: builtinAddVerb, Signature: &Signature{MinArgs: 3, MaxArgs: 3, ArgTypes: []int64{-1, 4, 4}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "delete_verb", Implementation: builtinDeleteVerb, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{-1, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "set_verb_info", Implementation: builtinSetVerbInfo, Signature: &Signature{MinArgs: 3, MaxArgs: 3, ArgTypes: []int64{-1, -1, 4}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "set_verb_args", Implementation: builtinSetVerbArgs, Signature: &Signature{MinArgs: 3, MaxArgs: 3, ArgTypes: []int64{-1, -1, 4}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "set_verb_code", Implementation: builtinSetVerbCode, Signature: &Signature{MinArgs: 3, MaxArgs: 3, ArgTypes: []int64{-1, -1, 4}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "disassemble", Implementation: builtinDisassemble, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{-1, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "generate_json", Implementation: builtinGenerateJson, Signature: &Signature{MinArgs: 1, MaxArgs: 3, ArgTypes: []int64{-1, 2, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "parse_json", Implementation: builtinParseJson, Signature: &Signature{MinArgs: 1, MaxArgs: 2, ArgTypes: []int64{2, 2}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "notify", Implementation: builtinNotify, Signature: &Signature{MinArgs: 2, MaxArgs: 4, ArgTypes: []int64{1, 2, -1, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "listeners", Implementation: builtinListeners, Signature: &Signature{MinArgs: 0, MaxArgs: 1, ArgTypes: []int64{-1}}, Visibility: Public, Effect: Transactional, Capability: config.Network},
		{Name: "listen", Implementation: builtinListen, Signature: &Signature{MinArgs: 2, MaxArgs: 3, ArgTypes: []int64{1, -1, 10}}, Visibility: Public, Effect: Irreversible, Capability: config.Network},
		{Name: "unlisten", Implementation: builtinUnlisten, Signature: &Signature{MinArgs: 1, MaxArgs: 2, ArgTypes: []int64{-1, -1}}, Visibility: Public, Effect: Irreversible, Capability: config.Network},
		{Name: "connected_players", Implementation: builtinConnectedPlayers, Signature: &Signature{MinArgs: 0, MaxArgs: 1, ArgTypes: []int64{-1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "connection_name", Implementation: builtinConnectionName, Signature: &Signature{MinArgs: 1, MaxArgs: 2, ArgTypes: []int64{1, 0}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "connection_name_lookup", Implementation: builtinConnectionNameLookup, Signature: &Signature{MinArgs: 1, MaxArgs: 2, ArgTypes: []int64{1, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "connection_options", Implementation: builtinConnectionOptions, Signature: &Signature{MinArgs: 1, MaxArgs: 2, ArgTypes: []int64{1, 2}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "boot_player", Implementation: builtinBootPlayer, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "switch_player", Implementation: builtinSwitchPlayer, Signature: &Signature{MinArgs: 2, MaxArgs: 3, ArgTypes: []int64{1, 1, 0}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "idle_seconds", Implementation: builtinIdleSeconds, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "connected_seconds", Implementation: builtinConnectedSeconds, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "connection_info", Implementation: builtinConnectionInfo, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "set_connection_option", Implementation: builtinSetConnectionOption, Signature: &Signature{MinArgs: 3, MaxArgs: 3, ArgTypes: []int64{1, 2, -1}}, Visibility: Public, Effect: Irreversible, Capability: config.Core},
		// This extension checks connection existence and permissions before the
		// option-name type. Admit both values here to retain that semantic order.
		{Name: "connection_option", Implementation: builtinConnectionOption, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{-1, -1}, PlainArityError: true}, Visibility: Hidden, Effect: Transactional, Capability: config.BarnExtensions},
		{Name: "open_network_connection", Implementation: builtinOpenNetworkConnection, Signature: &Signature{MinArgs: 2, MaxArgs: 3, ArgTypes: []int64{2, 0, 10}}, Visibility: Public, Effect: Irreversible, Capability: config.Network},
		{Name: "read_http", Implementation: builtinReadHTTP, Signature: &Signature{MinArgs: 1, MaxArgs: 2, ArgTypes: []int64{2, 1}}, Visibility: Public, Effect: Irreversible, Capability: config.Core},
		{Name: "flush_input", Implementation: builtinFlushInput, Signature: &Signature{MinArgs: 1, MaxArgs: 2, ArgTypes: []int64{1, -1}}, Visibility: Public, Effect: Irreversible, Capability: config.Core},
		{Name: "force_input", Implementation: builtinForceInput, Signature: &Signature{MinArgs: 2, MaxArgs: 3, ArgTypes: []int64{1, 2, -1}}, Visibility: Public, Effect: Irreversible, Capability: config.Core},
		{Name: "read", Implementation: builtinRead, Signature: &Signature{MinArgs: 0, MaxArgs: 2, ArgTypes: []int64{1, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "buffered_output_length", Implementation: builtinBufferedOutputLength, Signature: &Signature{MinArgs: 0, MaxArgs: 1, ArgTypes: []int64{1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "output_delimiters", Implementation: builtinOutputDelimiters, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "encode_base64", Implementation: builtinEncodeBase64, Signature: &Signature{MinArgs: 1, MaxArgs: 2, ArgTypes: []int64{2, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "decode_base64", Implementation: builtinDecodeBase64, Signature: &Signature{MinArgs: 1, MaxArgs: 2, ArgTypes: []int64{2, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "encode_binary", Implementation: builtinEncodeBinary, Signature: &Signature{MinArgs: 0, MaxArgs: -1, ArgTypes: []int64{}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "decode_binary", Implementation: builtinDecodeBinary, Signature: &Signature{MinArgs: 1, MaxArgs: 2, ArgTypes: []int64{2, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "crypt", Implementation: builtinCrypt, Signature: &Signature{MinArgs: 1, MaxArgs: 2, ArgTypes: []int64{2, 2}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "string_hash", Implementation: builtinStringHash, Signature: &Signature{MinArgs: 1, MaxArgs: 3, ArgTypes: []int64{2, 2, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "binary_hash", Implementation: builtinBinaryHash, Signature: &Signature{MinArgs: 1, MaxArgs: 3, ArgTypes: []int64{2, 2, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "value_hash", Implementation: builtinValueHash, Signature: &Signature{MinArgs: 1, MaxArgs: 3, ArgTypes: []int64{-1, 2, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "string_hmac", Implementation: builtinStringHmac, Signature: &Signature{MinArgs: 2, MaxArgs: 4, ArgTypes: []int64{2, 2, 2, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "binary_hmac", Implementation: builtinBinaryHmac, Signature: &Signature{MinArgs: 2, MaxArgs: 4, ArgTypes: []int64{2, 2, 2, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "value_hmac", Implementation: builtinValueHmac, Signature: &Signature{MinArgs: 2, MaxArgs: 4, ArgTypes: []int64{-1, 2, 2, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "salt", Implementation: builtinSalt, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{2, 2}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "random_bytes", Implementation: builtinRandomBytes, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{0}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "argon2", Implementation: builtinArgon2, Signature: &Signature{MinArgs: 2, MaxArgs: 5, ArgTypes: []int64{2, 2, 0, 0, 0}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "argon2_verify", Implementation: builtinArgon2Verify, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{2, 2}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "curl", Implementation: builtinCurl, Signature: &Signature{MinArgs: 1, MaxArgs: 3, ArgTypes: []int64{2, -1, 0}}, Visibility: Public, Effect: Irreversible, Capability: config.Network},
		{Name: "url_encode", Implementation: builtinUrlEncode, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{2}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "url_decode", Implementation: builtinUrlDecode, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{2}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "pcre_cache_stats", Implementation: builtinPcreCacheStats, Signature: &Signature{MinArgs: 0, MaxArgs: 0, ArgTypes: []int64{}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "pcre_match", Implementation: builtinPcreMatch, Signature: &Signature{MinArgs: 2, MaxArgs: 4, ArgTypes: []int64{2, 2, 0, 0}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "pcre_replace", Implementation: builtinPcreReplace, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{2, 2}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "file_open", Implementation: builtinFileOpen, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{2, 2}}, Visibility: Public, Effect: Irreversible, Capability: config.Core},
		{Name: "file_close", Implementation: builtinFileClose, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{0}}, Visibility: Public, Effect: Irreversible, Capability: config.Core},
		{Name: "file_name", Implementation: builtinFileName, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{0}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "file_openmode", Implementation: builtinFileOpenmode, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{0}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "file_read", Implementation: builtinFileRead, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{0, 0}}, Visibility: Public, Effect: Irreversible, Capability: config.Core},
		{Name: "file_readline", Implementation: builtinFileReadline, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{0}}, Visibility: Public, Effect: Irreversible, Capability: config.Core},
		{Name: "file_readlines", Implementation: builtinFileReadlines, Signature: &Signature{MinArgs: 3, MaxArgs: 3, ArgTypes: []int64{0, 0, 0}}, Visibility: Public, Effect: Irreversible, Capability: config.Core},
		{Name: "file_write", Implementation: builtinFileWrite, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{0, 2}}, Visibility: Public, Effect: Irreversible, Capability: config.Core},
		{Name: "file_writeline", Implementation: builtinFileWriteline, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{0, 2}}, Visibility: Public, Effect: Irreversible, Capability: config.Core},
		{Name: "file_flush", Implementation: builtinFileFlush, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{0}}, Visibility: Public, Effect: Irreversible, Capability: config.Core},
		{Name: "file_seek", Implementation: builtinFileSeek, Signature: &Signature{MinArgs: 3, MaxArgs: 3, ArgTypes: []int64{0, 0, 2}}, Visibility: Public, Effect: Irreversible, Capability: config.Core},
		{Name: "file_tell", Implementation: builtinFileTell, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{0}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "file_eof", Implementation: builtinFileEOF, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{0}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "file_size", Implementation: builtinFileSize, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{-1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "file_mode", Implementation: builtinFileMode, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{-1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "file_last_access", Implementation: builtinFileLastAccess, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{-1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "file_last_change", Implementation: builtinFileLastChange, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{-1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "file_last_modify", Implementation: builtinFileLastModify, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{-1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "file_stat", Implementation: builtinFileStat, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{-1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "file_type", Implementation: builtinFileType, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{-1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "file_remove", Implementation: builtinFileRemove, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{2}}, Visibility: Public, Effect: Irreversible, Capability: config.Core},
		{Name: "file_rename", Implementation: builtinFileRename, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{2, 2}}, Visibility: Public, Effect: Irreversible, Capability: config.Core},
		{Name: "file_mkdir", Implementation: builtinFileMkdir, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{2}}, Visibility: Public, Effect: Irreversible, Capability: config.Core},
		{Name: "file_rmdir", Implementation: builtinFileRmdir, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{2}}, Visibility: Public, Effect: Irreversible, Capability: config.Core},
		{Name: "file_chmod", Implementation: builtinFileChmod, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{2, 2}}, Visibility: Public, Effect: Irreversible, Capability: config.Core},
		{Name: "file_list", Implementation: builtinFileList, Signature: &Signature{MinArgs: 1, MaxArgs: 2, ArgTypes: []int64{2, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "file_handles", Implementation: builtinFileHandles, Signature: &Signature{MinArgs: 0, MaxArgs: 0, ArgTypes: []int64{}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "file_count_lines", Implementation: builtinFileCountLines, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{0}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "file_grep", Implementation: builtinFileGrep, Signature: &Signature{MinArgs: 2, MaxArgs: 3, ArgTypes: []int64{0, 2, 0}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "sqlite_open", Implementation: builtinSqliteOpen, Signature: &Signature{MinArgs: 1, MaxArgs: 2, ArgTypes: []int64{2, 0}}, Visibility: Public, Effect: Irreversible, Capability: config.SQLite},
		{Name: "sqlite_close", Implementation: builtinSqliteClose, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{0}}, Visibility: Public, Effect: Irreversible, Capability: config.SQLite},
		{Name: "sqlite_handles", Implementation: builtinSqliteHandles, Signature: &Signature{MinArgs: 0, MaxArgs: 0, ArgTypes: []int64{}}, Visibility: Public, Effect: Transactional, Capability: config.SQLite},
		{Name: "sqlite_info", Implementation: builtinSqliteInfo, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{0}}, Visibility: Public, Effect: Transactional, Capability: config.SQLite},
		{Name: "sqlite_query", Implementation: builtinSqliteQuery, Signature: &Signature{MinArgs: 2, MaxArgs: 3, ArgTypes: []int64{0, 2, -1}}, Visibility: Public, Effect: ImplementationOwned, Capability: config.SQLite},
		{Name: "sqlite_execute", Implementation: builtinSqliteExecute, Signature: &Signature{MinArgs: 3, MaxArgs: 3, ArgTypes: []int64{0, 2, 4}}, Visibility: Public, Effect: ImplementationOwned, Capability: config.SQLite},
		{Name: "sqlite_last_insert_row_id", Implementation: builtinSqliteLastInsertRowID, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{0}}, Visibility: Public, Effect: Transactional, Capability: config.SQLite},
		{Name: "sqlite_limit", Implementation: builtinSqliteLimit, Signature: &Signature{MinArgs: 3, MaxArgs: 3, ArgTypes: []int64{0, -1, 0}}, Visibility: Public, Effect: Irreversible, Capability: config.SQLite},
		{Name: "sqlite_interrupt", Implementation: builtinSqliteInterrupt, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{0}}, Visibility: Public, Effect: Irreversible, Capability: config.SQLite},
		{Name: "background_test", Implementation: builtinBackgroundTest, Signature: &Signature{MinArgs: 2, MaxArgs: 2, ArgTypes: []int64{2, 0}, PlainArityError: true}, Visibility: Public, Effect: Transactional, Capability: config.BackgroundTasks},
		{Name: "call_function", Implementation: builtinCallFunction, Signature: &Signature{MinArgs: 1, MaxArgs: -1, ArgTypes: []int64{2}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "function_info", Implementation: builtinFunctionInfo, Signature: &Signature{MinArgs: 0, MaxArgs: 1, ArgTypes: []int64{2}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "db_disk_size", Implementation: builtinDbDiskSize, Signature: &Signature{MinArgs: 0, MaxArgs: 0, ArgTypes: []int64{}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "dump_database", Implementation: builtinDumpDatabase, Signature: &Signature{MinArgs: 0, MaxArgs: 0, ArgTypes: []int64{}}, Visibility: Public, Effect: CommitGateReentrant, Capability: config.Core},
		{Name: "getenv", Implementation: builtinGetenv, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{2}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "read_stdin", Implementation: builtinReadStdin, Signature: &Signature{MinArgs: 0, MaxArgs: 0, ArgTypes: []int64{}}, Visibility: Hidden, Effect: Irreversible, Capability: config.ProcessStdin},
		{Name: "spellcheck", Implementation: builtinSpellcheck, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{2}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "set_thread_mode", Implementation: builtinSetThreadMode, Signature: &Signature{MinArgs: 0, MaxArgs: 1, ArgTypes: []int64{0}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "shutdown", Implementation: builtinShutdown, Signature: &Signature{MinArgs: 0, MaxArgs: 2, ArgTypes: []int64{2, -1}}, Visibility: Public, Effect: CommitGateReentrant, Capability: config.Core},
		{Name: "task_local", Implementation: builtinTaskLocal, Signature: &Signature{MinArgs: 0, MaxArgs: 0, ArgTypes: []int64{}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "set_task_local", Implementation: builtinSetTaskLocal, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{-1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "task_id", Implementation: builtinTaskID, Signature: &Signature{MinArgs: 0, MaxArgs: 0, ArgTypes: []int64{}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "ticks_left", Implementation: builtinTicksLeft, Signature: &Signature{MinArgs: 0, MaxArgs: 0, ArgTypes: []int64{}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "seconds_left", Implementation: builtinSecondsLeft, Signature: &Signature{MinArgs: 0, MaxArgs: 0, ArgTypes: []int64{}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "task_perms", Implementation: builtinTaskPerms, Signature: &Signature{MinArgs: 0, MaxArgs: 0, ArgTypes: []int64{}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "queue_info", Implementation: builtinQueueInfo, Signature: &Signature{MinArgs: 0, MaxArgs: 1, ArgTypes: []int64{1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "finished_tasks", Implementation: builtinFinishedTasks, Signature: &Signature{MinArgs: 0, MaxArgs: 0, ArgTypes: []int64{}, PlainArityError: true}, Visibility: Public, Effect: Transactional, Capability: config.BarnExtensions},
		{Name: "thread_pool", Implementation: builtinThreadPool, Signature: &Signature{MinArgs: 2, MaxArgs: 3, ArgTypes: []int64{2, 2, 0}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "threads", Implementation: builtinThreads, Signature: &Signature{MinArgs: 0, MaxArgs: 0, ArgTypes: []int64{}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "usage", Implementation: builtinUsage, Signature: &Signature{MinArgs: 0, MaxArgs: 0, ArgTypes: []int64{}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "malloc_stats", Implementation: builtinMallocStats, Signature: &Signature{MinArgs: 0, MaxArgs: 0, ArgTypes: []int64{}, PlainArityError: true}, Visibility: Public, Effect: Transactional, Capability: config.AllocatorStats},
		{Name: "memory_usage", Implementation: builtinMemoryUsage, Signature: &Signature{MinArgs: 0, MaxArgs: 0, ArgTypes: []int64{}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "log_cache_stats", Implementation: builtinLogCacheStats, Signature: &Signature{MinArgs: 0, MaxArgs: 0, ArgTypes: []int64{}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "exec", Implementation: builtinExec, Signature: &Signature{MinArgs: 1, MaxArgs: 3, ArgTypes: []int64{4, 2, 4}}, Visibility: Public, Effect: Irreversible, Capability: config.Core},
		{Name: "server_log", Implementation: builtinServerLog, Signature: &Signature{MinArgs: 1, MaxArgs: 2, ArgTypes: []int64{2, -1}}, Visibility: Public, Effect: Irreversible, Capability: config.Core},
		{Name: "server_version", Implementation: builtinServerVersion, Signature: &Signature{MinArgs: 0, MaxArgs: 1, ArgTypes: []int64{-1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "time", Implementation: builtinTime, Signature: &Signature{MinArgs: 0, MaxArgs: 0, ArgTypes: []int64{}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "ftime", Implementation: builtinFtime, Signature: &Signature{MinArgs: 0, MaxArgs: 1, ArgTypes: []int64{0}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "ctime", Implementation: builtinCtime, Signature: &Signature{MinArgs: 0, MaxArgs: 1, ArgTypes: []int64{0}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "load_server_options", Implementation: builtinLoadServerOptions, Signature: &Signature{MinArgs: 0, MaxArgs: 0, ArgTypes: []int64{}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "locate_by_name", Implementation: builtinLocateByName, Signature: &Signature{MinArgs: 1, MaxArgs: 2, ArgTypes: []int64{2, 0}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "locations", Implementation: builtinLocations, Signature: &Signature{MinArgs: 1, MaxArgs: 3, ArgTypes: []int64{1, 1, 0}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "owned_objects", Implementation: builtinOwnedObjects, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "next_recycled_object", Implementation: builtinNextRecycledObject, Signature: &Signature{MinArgs: 0, MaxArgs: 1, ArgTypes: []int64{1}, Alternatives: map[int][]int64{0: {0}}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "recycled_objects", Implementation: builtinRecycledObjects, Signature: &Signature{MinArgs: 0, MaxArgs: 0, ArgTypes: []int64{}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "recreate", Implementation: builtinRecreate, Signature: &Signature{MinArgs: 2, MaxArgs: 3, ArgTypes: []int64{1, 1, 1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "waif_stats", Implementation: builtinWaifStats, Signature: &Signature{MinArgs: 0, MaxArgs: 0, ArgTypes: []int64{}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "verb_cache_stats", Implementation: builtinVerbCacheStats, Signature: &Signature{MinArgs: 0, MaxArgs: 0, ArgTypes: []int64{}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "reset_max_object", Implementation: builtinResetMaxObject, Signature: &Signature{MinArgs: 0, MaxArgs: 0, ArgTypes: []int64{}}, Visibility: Public, Effect: Irreversible, Capability: config.Core},
		{Name: "value_bytes", Implementation: builtinValueBytes, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{-1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "run_gc", Implementation: builtinRunGC, Signature: &Signature{MinArgs: 0, MaxArgs: 0, ArgTypes: []int64{}}, Visibility: Public, Effect: ImplementationOwned, Capability: config.Core},
		{Name: "gc_stats", Implementation: builtinGCStats, Signature: &Signature{MinArgs: 0, MaxArgs: 0, ArgTypes: []int64{}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "queued_tasks", Implementation: builtinQueuedTasks, Signature: &Signature{MinArgs: 0, MaxArgs: 2, ArgTypes: []int64{0, 0}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "kill_task", Implementation: builtinKillTask, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{0}}, Visibility: Public, Effect: ImplementationOwned, Capability: config.Core},
		{Name: "task_stack", Implementation: builtinTaskStack, Signature: &Signature{MinArgs: 1, MaxArgs: 3, ArgTypes: []int64{0, -1, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core, LineSync: true},
		{Name: "suspend", Implementation: builtinSuspend, Signature: &Signature{MinArgs: 0, MaxArgs: 1, ArgTypes: []int64{-2}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "resume", Implementation: builtinResume, Signature: &Signature{MinArgs: 1, MaxArgs: 2, ArgTypes: []int64{0, -1}}, Visibility: Public, Effect: Irreversible, Capability: config.Core},
		{Name: "callers", Implementation: builtinCallers, Signature: &Signature{MinArgs: 0, MaxArgs: 1, ArgTypes: []int64{-1}}, Visibility: Public, Effect: Transactional, Capability: config.Core, LineSync: true},
		{Name: "set_task_perms", Implementation: builtinSetTaskPerms, Signature: &Signature{MinArgs: 1, MaxArgs: 1, ArgTypes: []int64{1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "caller_perms", Implementation: builtinCallerPerms, Signature: &Signature{MinArgs: 0, MaxArgs: 0, ArgTypes: []int64{}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "raise", Implementation: builtinRaise, Signature: &Signature{MinArgs: 1, MaxArgs: 3, ArgTypes: []int64{-1, 2, -1}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
		{Name: "yin", Implementation: builtinYin, Signature: &Signature{MinArgs: 0, MaxArgs: 3, ArgTypes: []int64{-2, 0, 0}}, Visibility: Public, Effect: Transactional, Capability: config.Core},
	}
}
