// Code generated from ToastStunt builtin registrations; DO NOT EDIT.
package builtins

var toastBuiltinSignatures = map[string]builtinSignature{
	"abs":                       {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgNumeric}},
	"acos":                      {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgFloat}},
	"acosh":                     {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgFloat}},
	"add_property":              {MinArgs: 4, MaxArgs: 4, ArgTypes: []builtinArgKind{builtinArgAny, builtinArgStr, builtinArgAny, builtinArgList}},
	"add_verb":                  {MinArgs: 3, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgAny, builtinArgList, builtinArgList}},
	"all_members":               {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgAny, builtinArgList}},
	"ancestors":                 {MinArgs: 1, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgAny, builtinArgAny}},
	"argon2":                    {MinArgs: 2, MaxArgs: 5, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgStr, builtinArgInt, builtinArgInt, builtinArgInt}},
	"argon2_verify":             {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgStr}},
	"asin":                      {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgFloat}},
	"asinh":                     {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgFloat}},
	"atan":                      {MinArgs: 1, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgFloat, builtinArgFloat}},
	"atan2":                     {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgFloat, builtinArgFloat}},
	"atanh":                     {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgFloat}},
	"background_test":           {MinArgs: 0, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgInt}},
	"binary_hash":               {MinArgs: 1, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgStr, builtinArgAny}},
	"binary_hmac":               {MinArgs: 2, MaxArgs: 4, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgStr, builtinArgStr, builtinArgAny}},
	"boot_player":               {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgObj}},
	"buffered_output_length":    {MinArgs: 0, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgObj}},
	"call_function":             {MinArgs: 1, MaxArgs: -1, ArgTypes: []builtinArgKind{builtinArgStr}},
	"caller_perms":              {MinArgs: 0, MaxArgs: 0},
	"callers":                   {MinArgs: 0, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgAny}},
	"cbrt":                      {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgFloat}},
	"ceil":                      {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgFloat}},
	"children":                  {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgAny}},
	"chparent":                  {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgAny, builtinArgObj}},
	"chparents":                 {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgAny, builtinArgList}},
	"chr":                       {MinArgs: 0, MaxArgs: -1},
	"clear_property":            {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgAny, builtinArgStr}},
	"connected_players":         {MinArgs: 0, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgAny}},
	"connected_seconds":         {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgObj}},
	"connection_info":           {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgObj}},
	"connection_name":           {MinArgs: 1, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgObj, builtinArgInt}},
	"connection_name_lookup":    {MinArgs: 1, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgObj, builtinArgAny}},
	"connection_options":        {MinArgs: 1, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgObj, builtinArgStr}},
	"cos":                       {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgFloat}},
	"cosh":                      {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgFloat}},
	"create":                    {MinArgs: 1, MaxArgs: 4, ArgTypes: []builtinArgKind{builtinArgAny, builtinArgAny, builtinArgAny, builtinArgAny}},
	"crypt":                     {MinArgs: 1, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgStr}},
	"ctime":                     {MinArgs: 0, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgInt}},
	"curl":                      {MinArgs: 1, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgAny, builtinArgInt}},
	"db_disk_size":              {MinArgs: 0, MaxArgs: 0},
	"decode_base64":             {MinArgs: 1, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgAny}},
	"decode_binary":             {MinArgs: 1, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgAny}},
	"delete_property":           {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgAny, builtinArgStr}},
	"delete_verb":               {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgAny, builtinArgAny}},
	"descendants":               {MinArgs: 1, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgAny, builtinArgAny}},
	"disassemble":               {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgAny, builtinArgAny}},
	"distance":                  {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgList, builtinArgList}},
	"dump_database":             {MinArgs: 0, MaxArgs: 0},
	"encode_base64":             {MinArgs: 1, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgAny}},
	"encode_binary":             {MinArgs: 0, MaxArgs: -1},
	"equal":                     {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgAny, builtinArgAny}},
	"eval":                      {MinArgs: 1, MaxArgs: -1, ArgTypes: []builtinArgKind{builtinArgStr}},
	"exec":                      {MinArgs: 1, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgList, builtinArgStr, builtinArgList}},
	"exp":                       {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgFloat}},
	"explode":                   {MinArgs: 1, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgStr, builtinArgInt}},
	"file_chmod":                {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgStr}},
	"file_close":                {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgInt}},
	"file_count_lines":          {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgInt}},
	"file_eof":                  {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgInt}},
	"file_flush":                {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgInt}},
	"file_grep":                 {MinArgs: 2, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgInt, builtinArgStr, builtinArgInt}},
	"file_handles":              {MinArgs: 0, MaxArgs: 0},
	"file_last_access":          {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgAny}},
	"file_last_change":          {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgAny}},
	"file_last_modify":          {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgAny}},
	"file_list":                 {MinArgs: 1, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgAny}},
	"file_mkdir":                {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgStr}},
	"file_mode":                 {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgAny}},
	"file_name":                 {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgInt}},
	"file_open":                 {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgStr}},
	"file_openmode":             {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgInt}},
	"file_read":                 {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgInt, builtinArgInt}},
	"file_readline":             {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgInt}},
	"file_readlines":            {MinArgs: 3, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgInt, builtinArgInt, builtinArgInt}},
	"file_remove":               {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgStr}},
	"file_rename":               {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgStr}},
	"file_rmdir":                {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgStr}},
	"file_seek":                 {MinArgs: 3, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgInt, builtinArgInt, builtinArgStr}},
	"file_size":                 {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgAny}},
	"file_stat":                 {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgAny}},
	"file_tell":                 {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgInt}},
	"file_type":                 {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgAny}},
	"file_write":                {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgInt, builtinArgStr}},
	"file_writeline":            {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgInt, builtinArgStr}},
	"finished_tasks":            {MinArgs: 0, MaxArgs: 0},
	"floatstr":                  {MinArgs: 2, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgFloat, builtinArgInt, builtinArgAny}},
	"floor":                     {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgFloat}},
	"flush_input":               {MinArgs: 1, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgObj, builtinArgAny}},
	"force_input":               {MinArgs: 2, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgObj, builtinArgStr, builtinArgAny}},
	"frandom":                   {MinArgs: 1, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgFloat, builtinArgFloat}},
	"ftime":                     {MinArgs: 0, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgInt}},
	"function_info":             {MinArgs: 0, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgStr}},
	"gc_stats":                  {MinArgs: 0, MaxArgs: 0},
	"generate_json":             {MinArgs: 1, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgAny, builtinArgStr, builtinArgAny}},
	"getenv":                    {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgStr}},
	"idle_seconds":              {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgObj}},
	"index":                     {MinArgs: 2, MaxArgs: 4, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgStr, builtinArgAny, builtinArgInt}},
	"is_clear_property":         {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgAny, builtinArgStr}},
	"is_member":                 {MinArgs: 2, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgAny, builtinArgAny, builtinArgInt}},
	"is_player":                 {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgObj}},
	"isa":                       {MinArgs: 2, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgAny, builtinArgAny, builtinArgInt}},
	"kill_task":                 {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgInt}},
	"length":                    {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgAny}},
	"listappend":                {MinArgs: 2, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgList, builtinArgAny, builtinArgInt}},
	"listdelete":                {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgList, builtinArgInt}},
	"listen":                    {MinArgs: 2, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgObj, builtinArgAny, builtinArgMap}},
	"listeners":                 {MinArgs: 0, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgAny}},
	"listinsert":                {MinArgs: 2, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgList, builtinArgAny, builtinArgInt}},
	"listset":                   {MinArgs: 3, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgList, builtinArgAny, builtinArgInt}},
	"load_server_options":       {MinArgs: 0, MaxArgs: 0},
	"locate_by_name":            {MinArgs: 1, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgInt}},
	"locations":                 {MinArgs: 1, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgObj, builtinArgObj, builtinArgInt}},
	"log":                       {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgFloat}},
	"log10":                     {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgFloat}},
	"log_cache_stats":           {MinArgs: 0, MaxArgs: 0},
	"malloc_stats":              {MinArgs: 0, MaxArgs: 0},
	"mapdelete":                 {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgMap, builtinArgAny}},
	"maphaskey":                 {MinArgs: 2, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgMap, builtinArgAny, builtinArgInt}},
	"mapkeys":                   {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgMap}},
	"mapvalues":                 {MinArgs: 1, MaxArgs: -1, ArgTypes: []builtinArgKind{builtinArgMap}},
	"match":                     {MinArgs: 2, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgStr, builtinArgAny}},
	"max":                       {MinArgs: 1, MaxArgs: -1, ArgTypes: []builtinArgKind{builtinArgNumeric}},
	"max_object":                {MinArgs: 0, MaxArgs: 0},
	"memory_usage":              {MinArgs: 0, MaxArgs: 0},
	"min":                       {MinArgs: 1, MaxArgs: -1, ArgTypes: []builtinArgKind{builtinArgNumeric}},
	"move":                      {MinArgs: 2, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgObj, builtinArgObj, builtinArgInt}},
	"new_waif":                  {MinArgs: 0, MaxArgs: 0},
	"next_recycled_object":      {MinArgs: 0, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgObj}},
	"notify":                    {MinArgs: 2, MaxArgs: 4, ArgTypes: []builtinArgKind{builtinArgObj, builtinArgStr, builtinArgAny, builtinArgAny}},
	"object_bytes":              {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgAny}},
	"occupants":                 {MinArgs: 1, MaxArgs: 4, ArgTypes: []builtinArgKind{builtinArgList, builtinArgAny, builtinArgInt, builtinArgInt}},
	"open_network_connection":   {MinArgs: 2, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgInt, builtinArgMap}},
	"output_delimiters":         {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgObj}},
	"owned_objects":             {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgObj}},
	"parent":                    {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgAny}},
	"parents":                   {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgAny}},
	"parse_ansi":                {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgStr}},
	"parse_json":                {MinArgs: 1, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgStr}},
	"pass":                      {MinArgs: 0, MaxArgs: -1},
	"pcre_cache_stats":          {MinArgs: 0, MaxArgs: 0},
	"pcre_match":                {MinArgs: 2, MaxArgs: 4, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgStr, builtinArgInt, builtinArgInt}},
	"pcre_replace":              {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgStr}},
	"players":                   {MinArgs: 0, MaxArgs: 0},
	"properties":                {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgAny}},
	"property_info":             {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgAny, builtinArgStr}},
	"queue_info":                {MinArgs: 0, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgObj}},
	"queued_tasks":              {MinArgs: 0, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgInt, builtinArgInt}},
	"raise":                     {MinArgs: 1, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgAny, builtinArgStr, builtinArgAny}},
	"random":                    {MinArgs: 0, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgInt, builtinArgInt}},
	"random_bytes":              {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgInt}},
	"read":                      {MinArgs: 0, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgObj, builtinArgAny}},
	"read_http":                 {MinArgs: 1, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgObj}},
	"read_stdin":                {MinArgs: 0, MaxArgs: 0},
	"recreate":                  {MinArgs: 2, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgObj, builtinArgObj, builtinArgObj}},
	"recycle":                   {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgAny}},
	"recycled_objects":          {MinArgs: 0, MaxArgs: 0},
	"relative_heading":          {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgList, builtinArgList}},
	"remove_ansi":               {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgStr}},
	"renumber":                  {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgObj}},
	"reseed_random":             {MinArgs: 0, MaxArgs: 0},
	"reset_max_object":          {MinArgs: 0, MaxArgs: 0},
	"respond_to":                {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgAny, builtinArgStr}},
	"resume":                    {MinArgs: 1, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgInt, builtinArgAny}},
	"reverse":                   {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgAny}},
	"rindex":                    {MinArgs: 2, MaxArgs: 4, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgStr, builtinArgAny, builtinArgInt}},
	"rmatch":                    {MinArgs: 2, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgStr, builtinArgAny}},
	"round":                     {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgFloat}},
	"run_gc":                    {MinArgs: 0, MaxArgs: 0},
	"salt":                      {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgStr}},
	"seconds_left":              {MinArgs: 0, MaxArgs: 0},
	"server_log":                {MinArgs: 1, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgAny}},
	"server_version":            {MinArgs: 0, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgAny}},
	"set_connection_option":     {MinArgs: 3, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgObj, builtinArgStr, builtinArgAny}},
	"set_player_flag":           {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgObj, builtinArgAny}},
	"set_property_info":         {MinArgs: 3, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgAny, builtinArgStr, builtinArgList}},
	"set_task_local":            {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgAny}},
	"set_task_perms":            {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgObj}},
	"set_thread_mode":           {MinArgs: 0, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgInt}},
	"set_verb_args":             {MinArgs: 3, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgAny, builtinArgAny, builtinArgList}},
	"set_verb_code":             {MinArgs: 3, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgAny, builtinArgAny, builtinArgList}},
	"set_verb_info":             {MinArgs: 3, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgAny, builtinArgAny, builtinArgList}},
	"setadd":                    {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgList, builtinArgAny}},
	"setremove":                 {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgList, builtinArgAny}},
	"shutdown":                  {MinArgs: 0, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgAny}},
	"simplex_noise":             {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgList}},
	"sin":                       {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgFloat}},
	"sinh":                      {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgFloat}},
	"slice":                     {MinArgs: 1, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgList, builtinArgAny, builtinArgAny}},
	"sort":                      {MinArgs: 1, MaxArgs: 4, ArgTypes: []builtinArgKind{builtinArgList, builtinArgList, builtinArgInt, builtinArgInt}},
	"spellcheck":                {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgStr}},
	"sqlite_close":              {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgInt}},
	"sqlite_execute":            {MinArgs: 3, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgInt, builtinArgStr, builtinArgList}},
	"sqlite_handles":            {MinArgs: 0, MaxArgs: 0},
	"sqlite_info":               {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgInt}},
	"sqlite_interrupt":          {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgInt}},
	"sqlite_last_insert_row_id": {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgInt}},
	"sqlite_limit":              {MinArgs: 3, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgInt, builtinArgAny, builtinArgInt}},
	"sqlite_open":               {MinArgs: 1, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgInt}},
	"sqlite_query":              {MinArgs: 2, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgInt, builtinArgStr, builtinArgAny}},
	"sqrt":                      {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgFloat}},
	"strcmp":                    {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgStr}},
	"string_hash":               {MinArgs: 1, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgStr, builtinArgAny}},
	"string_hmac":               {MinArgs: 2, MaxArgs: 4, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgStr, builtinArgStr, builtinArgAny}},
	"strsub":                    {MinArgs: 3, MaxArgs: 4, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgStr, builtinArgStr, builtinArgAny}},
	"strtr":                     {MinArgs: 3, MaxArgs: 4, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgStr, builtinArgStr, builtinArgAny}},
	"substitute":                {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgList}},
	"suspend":                   {MinArgs: 0, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgNumeric}},
	"switch_player":             {MinArgs: 2, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgObj, builtinArgObj, builtinArgInt}},
	"tan":                       {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgFloat}},
	"tanh":                      {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgFloat}},
	"task_id":                   {MinArgs: 0, MaxArgs: 0},
	"task_local":                {MinArgs: 0, MaxArgs: 0},
	"task_perms":                {MinArgs: 0, MaxArgs: 0},
	"task_stack":                {MinArgs: 1, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgInt, builtinArgAny, builtinArgAny}},
	"thread_pool":               {MinArgs: 2, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgStr, builtinArgInt}},
	"threads":                   {MinArgs: 0, MaxArgs: 0},
	"ticks_left":                {MinArgs: 0, MaxArgs: 0},
	"time":                      {MinArgs: 0, MaxArgs: 0},
	"tofloat":                   {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgAny}},
	"toint":                     {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgAny}},
	"toliteral":                 {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgAny}},
	"toobj":                     {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgAny}},
	"tostr":                     {MinArgs: 0, MaxArgs: -1},
	"trunc":                     {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgFloat}},
	"typeof":                    {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgAny}},
	"unlisten":                  {MinArgs: 1, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgAny, builtinArgAny}},
	"url_decode":                {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgStr}},
	"url_encode":                {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgStr}},
	"usage":                     {MinArgs: 0, MaxArgs: 0},
	"valid":                     {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgAny}},
	"value_bytes":               {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgAny}},
	"value_hash":                {MinArgs: 1, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgAny, builtinArgStr, builtinArgAny}},
	"value_hmac":                {MinArgs: 2, MaxArgs: 4, ArgTypes: []builtinArgKind{builtinArgAny, builtinArgStr, builtinArgStr, builtinArgAny}},
	"verb_args":                 {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgAny, builtinArgAny}},
	"verb_cache_stats":          {MinArgs: 0, MaxArgs: 0},
	"verb_code":                 {MinArgs: 2, MaxArgs: 4, ArgTypes: []builtinArgKind{builtinArgAny, builtinArgAny, builtinArgAny, builtinArgAny}},
	"verb_info":                 {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgAny, builtinArgAny}},
	"verbs":                     {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgAny}},
	"waif_stats":                {MinArgs: 0, MaxArgs: 0},
	"yin":                       {MinArgs: 0, MaxArgs: 3, ArgTypes: []builtinArgKind{builtinArgNumeric, builtinArgInt, builtinArgInt}},
}

var barnBuiltinSignatures = map[string]builtinSignature{
	"capitalize":        {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgStr}},
	"connection_option": {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgObj, builtinArgStr}},
	"downcase":          {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgStr}},
	"implode":           {MinArgs: 1, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgList, builtinArgStr}},
	"ltrim":             {MinArgs: 1, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgStr}},
	"mapmerge":          {MinArgs: 2, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgMap, builtinArgMap}},
	"rtrim":             {MinArgs: 1, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgStr}},
	"trim":              {MinArgs: 1, MaxArgs: 2, ArgTypes: []builtinArgKind{builtinArgStr, builtinArgStr}},
	"unique":            {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgList}},
	"upcase":            {MinArgs: 1, MaxArgs: 1, ArgTypes: []builtinArgKind{builtinArgStr}},
}
